
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: spannerautoscalers.spanner.mercari.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.scaleTargetRef.projectId
    name: Project Id
    type: string
  - JSONPath: .spec.scaleTargetRef.instanceId
    name: Instance Id
    type: string
  - JSONPath: .spec.minNodes
    name: Min Nodes
    type: integer
  - JSONPath: .spec.maxNodes
    name: Max Nodes
    type: integer
  - JSONPath: .spec.targetCPUUtilization.highPriority
    name: Target CPU
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: spanner.mercari.com
  names:
    kind: SpannerAutoscaler
    listKind: SpannerAutoscalerList
    plural: spannerautoscalers
    singular: spannerautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SpannerAutoscaler is the Schema for the spannerautoscalers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SpannerAutoscalerSpec defines the desired state of SpannerAutoscaler
          properties:
            maxNodes:
              description: upper limit for the number of nodes that can be set by
                the autoscaler. It cannot be smaller than MinNodes.
              format: int32
              minimum: 1
              type: integer
            maxScaleDownNodes:
              description: upper limit for the number of nodes when autoscaler scaledown.
              format: int32
              minimum: 1
              type: integer
            minNodes:
              description: lower limit for the number of nodes that can be set by
                the autoscaler.
              format: int32
              minimum: 1
              type: integer
            scaleTargetRef:
              description: target reference for scaling.
              properties:
                instanceId:
                  minLength: 1
                  type: string
                projectId:
                  minLength: 1
                  type: string
              required:
              - instanceId
              - projectId
              type: object
            serviceAccountSecretRef:
              description: reference for service account secret. If not specified,
                use ADC of the controller.
              properties:
                key:
                  minLength: 1
                  type: string
                name:
                  minLength: 1
                  type: string
                namespace:
                  type: string
              required:
              - key
              - name
              type: object
            targetCPUUtilization:
              description: target average CPU utilization for Spanner.
              properties:
                highPriority:
                  description: fraction of the requested CPU that should be utilized/used,
                    e.g. 70 means that 70% of the requested CPU should be in use.
                  format: int32
                  maximum: 100
                  minimum: 0
                  type: integer
              required:
              - highPriority
              type: object
          required:
          - maxNodes
          - minNodes
          - scaleTargetRef
          - serviceAccountSecretRef
          - targetCPUUtilization
          type: object
        status:
          description: SpannerAutoscalerStatus defines the observed state of SpannerAutoscaler
          properties:
            currentHighPriorityCPUUtilization:
              description: current average CPU utilization for high priority task,
                represented as a percentage.
              format: int32
              type: integer
            currentNodes:
              description: current number of nodes of Spanner managed by this autoscaler.
              format: int32
              type: integer
            desiredNodes:
              description: desired number of nodes of Spanner managed by this autoscaler.
              format: int32
              type: integer
            instanceState:
              type: string
            lastScaleTime:
              description: last time the SpannerAutoscaler scaled the number of Spanner
                nodes. used by the autoscaler to control how often the number of nodes
                is changed.
              format: date-time
              type: string
            lastSyncTime:
              description: last time the SpannerAutoscaler synced the Spanner status.
              format: date-time
              type: string
          required:
          - instanceState
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
