name: Create SemVer Tag

on:
  push:
    branches:
      - master

jobs:
  bump-tag:
    runs-on: ubuntu-18.04
    outputs:
      new_version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Merged Pull Request
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter 'release' Labels on PR
        uses: actions-ecosystem/action-release-label@v1
        id: bump-label
        if: ${{ steps.get-merged-pull-request.outputs.title != null }}
        with:
          labels: ${{ steps.get-merged-pull-request.outputs.labels }}

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.bump-label.outputs.level != null }}
        with:
          semver_only: true

      - name: Bump Semantic Version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.bump-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.bump-label.outputs.level }}

      - name: Push New Tag
        uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: "${{ steps.bump-semver.outputs.new_version }}: PR #${{ steps.get-merged-pull-request.outputs.number }} ${{ steps.get-merged-pull-request.outputs.title }}"

      - name: Comment on Pull Request
        uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.get-merged-pull-request.outputs.number }}
          body: |
            A tag with version [${{ steps.bump-semver.outputs.new_version }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.bump-semver.outputs.new_version }}) has been created! :tada:

            Changes: https://github.com/${{ github.repository }}/compare/${{ steps.get-latest-tag.outputs.tag }}...${{ steps.bump-semver.outputs.new_version }}

  release:
    needs: bump-tag
    if: ${{ needs.bump-tag.outputs.new_version != null }}
    uses: mercari/spanner-autoscaler/.github/workflows/release.yml@master
    with:
      version: ${{ needs.bump-tag.outputs.new_version }}
